##Archivos
## no cambiar los titulos de cada uno de los diccionarios
carpeta:
  insumos
  
datos: # 
  balanced_score: 'BSC_EXITO.xlsx'
  margen : 'Margen.xlsx'
  precios : 'Precios_exito.xlsx'


columnas_fechas:
  - Mes

filtros:
  negocio: ['Otros Oper Cciales']

balanced_score_fill:
  borrar_na: ['negocio']
  filla_na_0: ['venta_cop','venta_un']

balanced_score_columnas:
    Mes : [str,'mes'] 
    EAN : [str,EAN]
    Codigo SAP : [str,'cod_material']
    Nombre Producto : [str,nombre_material]
    PLU : [str,PLU]    
    Negocio : [str,'negocio']
    Categoria : [str,'categoria']
    Sub Categoria : [str,'sub_categoria']
    Marca : [str,'marca']
    Ventas COP: [float64,'venta_cop']
    Ventas UN : [float64,'venta_un']

config_margen:
  margen_sector: # hoja y columnas de margen por sector
    cod_negocio: str
    negocio: str
    marge_real_negocio: float64
    margen_ppto: float64
  margen_marca:  # hoja y columnas de margen por marca
    cod_marca: str
    marca: str
    margen_real: float64
    margen_ppto: float64
  margen_material: # hoja y columnas de margen por material
    cod_material: str
    nombre_material: str
    margen_real: float64
    margen_ppto: float64
  
agrupaciones:
  agrupa_a : 
    var_numericas:
      - venta_cop
    var_categoricas:
      - mes_agrupado
      - negocio


