##Archivos
## no cambiar los titulos de cada uno de los diccionarios
carpeta:
  insumos
  
datos: # 
  balanced_score: 'BSC_EXITO.xlsx'
  margen : 'Margen.xlsx'
  precios : 'Precios_exito.xlsx'

balanced_score_columnas:
    Mes : [int,'mes']  
    Región : [str, region]
    Negocio : [str,'negocio']
    Marca : [str,'marca']
    Producto: [str,'producto']
    Código SAP (Producto) : [str,'codigo_sap']
    Peso: [float,'peso']
    Venta ($) Anterior: [float64,'venta_cop_año_ant']
    Venta ($) Actual: [float64,'venta_cop_año_act']
    Venta (Un.) Anterior : [float64,'venta_un_ant']
    Venta (Un.) Actual : [float64,'venta_un_act']



config_margen:
  margen_sector: # hoja y columnas de margen por sector
    cod_negocio: str
    negocio: str
    marge_real: float64
    margen_ppto: float64
  margen_marca:  # hoja y columnas de margen por marca
    cod_marca: str
    marca: str
    margen_real: float64
    margen_ppto: float64
  margen_material: # hoja y columnas de margen por material
    cod_material: str
    nombre_material: str
    margen_real: float64
    margen_ppto: float64
  
ajustes_balanced_scored:  
  - borrar_na: ['region', 'negocio']   
  - filla_na_0: ['venta_cop_año_ant','venta_un_ant']
  - filtros: {'negocio': 'Otros Oper Cciales'}
  


